config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    before_save { self.email = email.downcase }	

    def failed_login
      self.update(failed_login_attempts: self.failed_login_attempts + 1)
    end

    def successful_login
      self.update(succesful_login_attempts: self.succesful_login_attempts + 1)
    end

    def send_reset_token
        self.reset_token = User.new_token
        update_attribute(:reset_sent_at, Time.zone.now)
        self.save!
        UserMailer.password_reset(self).deliver_now
      end
    
      def password_reset_expired?
        reset_sent_at < 2.hours.ago
      end
      
      def User.new_token
        SecureRandom.urlsafe_base64
      end


      private
    
        # Converts email to all lower-case.
        def downcase_email
          self.email = email.downcase
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end
  
    def authorize
      redirect_to log_in_path unless current_user
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authorize

    def index
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    before_action :valid_token,   only: [:edit, :update]

    def new
    end
  
    def create
      @user = User.find_by(email: params[:password_reset][:email].downcase)
      if @user
        @user.send_reset_token
        flash[:info] = "Email sent with password reset instructions"
        redirect_to root_url
      else
        flash.now[:danger] = "Email address not found"
        render 'new'
      end
    end
  
    def edit
    end
  
    def update
      if params[:user][:password].empty?                  
        @user.errors.add(:password, "can't be empty")
        render 'edit'
      elsif @user.update(user_params)
        session[:user_id] = @user.id
        flash[:success] = "Password has been reset."
        redirect_to root_path
      else
        render 'edit'
      end
    end
  
      private
  
        def user_params
          params.require(:user).permit(:email, :password, :password_confirmation)
        end	
  
      def valid_token
      @user = User.find_by(reset_token: params[:id])
      if !@user 
        flash.now[:danger] = "Invalid token"
        redirect_to root_url
      elsif @user.password_reset_expired? 
        flash.now[:danger] = "Expired token"
        redirect_to root_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
  
    def create
        @user = User.find_by(email: params[:email])
        if @user && @user.authenticate(params[:password])
            @user.successful_login
            session[:user_id] = @user.id 
            redirect_to root_path, :notice => "Logged in!"
        else
            if @user
                @user.failed_login
            end
                flash.now.alert = "Invalid email or password"
            render "new"
        end
    end
  
    def destroy 
      session[:user_id] = nil
        redirect_to root_url, :notice => "Logged out!"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :authorize, only: %i[ index show edit destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.json {render json: UsersDatatable.new(view_context)}
    end
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {}).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">
    <h1> Hello Rails! </h1>
    <p> Welcome to the Rails 6 template! If you can see a wonderful datatable below then Bootstrap, Jquery, & Datatables have been installed! </p>
    <div class="row">
        <div class="col-md-6">Bootstrap</div>
        <div class="col-md-6">Has Been Loaded</div>
    </div>
    <br>
   <table id="users" class="table" style="width: 100%;" data-source="<%= users_url(format: "json") %>">
        <thead>
            <tr>
                <th>Email</th>
                <th>Created At</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SolutionstreetRailstemplate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/password_resets/edit.html.erb
<div class="container">
  <h1>Reset password</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>

        <%= hidden_field_tag :email, @user.email %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %><br><br>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %><br><br>
        <%= f.submit "Update password", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/password_resets/new.html.erb
<div class="container">
  <h1>Forgot password</h1>
  <br>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(:password_reset, url: password_resets_path) do |f| %>
        <div class="row">
          <div class="col-md-2">
            <%= f.label :email %>
          </div>
          <div class="col-md-10">
            <%= f.email_field :email, class: 'form-control' %>
          </div>
        </div><br>
        <div class="row">
          <%= f.submit "Submit", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
      <%= form.label :email %>
      <%= form.text_field :email, class: 'form-control' %><br><br>
      <%= form.label :password, "Confirmation" %>
      <%= form.password_field :password, class: 'form-control' %><br><br>
      <%= form.submit "Sign Up", class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Users</h1>

  <table id="users" class="table" style="width: 100%;" data-source="<%= users_url(format: "json") %>">
          <thead>
              <tr>
                  <th>Email</th>
                  <th>Created At</th>
                  <th></th>
              </tr>
          </thead>
          <tbody>
          </tbody>
      </table>

  <br>

  <%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<div class="container">
    <h1>New User</h1>
    <%= render 'form', user: @user %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>